In [ ]:
# Array is data structures that stores the element in the sequential order.

# Numpy is a python library used for working with Arrays.

In [2]:
import numpy as np

In [3]:
numbers = [1,2,3,4,5]
np_array = np.array(numbers)
print(np_array)

[1 2 3 4 5]


In [8]:
np.zeros(8)


array([0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
 np.zeros((3,4))  # initial formation of the array remains the same


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
x = np.ones((3,3),int)

x[2] = 2
print(x)

[[1 1 1]
 [1 1 1]
 [2 2 2]]


In [10]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [13]:
x = np.ones(5)
x.dtype          # dtype is used to check the type of the numpy array

dtype('float64')

In [43]:
# creating arrays

arr = np.array(23)                         # 0-D array

arr1 = np.array([1,2,3,4,5])               # 1-D array

arr2 = np.array([[1,2,3],[4,5,6]])           # 2-D array

print(arr)
print(arr1)
print(arr2)

23
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [44]:
print(arr.ndim)    # ndim is used to return the dimensions of the array

print(arr2.ndim)


0
2


**Access array elements**

In [38]:


print(arr1[0])
print(arr2[0][2])


1
3


In [45]:
# shape gives the number of rows and columns

print(arr.shape)
print(arr2.shape)
print(x.shape)

()
(2, 3)
(3, 3)


**Array slicing**


In [56]:
array1 = np.array([1,2,3,4,5,6,7])   # 1-D array

print(array1[0])
print(array1[1:5])
print(array1[4:])
print(array1[:4])
print(array1[1:5:2])

print(array1[-3:-1])
print(array1[:-3])

1
[2 3 4 5]
[5 6 7]
[1 2 3 4]
[2 4]
[5 6]
[1 2 3 4]


In [60]:
array2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [63]:
print(array2[1,1:4])

print(array2[0:2,2])

print(array2[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


**Boolean Indexing**

In [3]:
num = np.array([1,2,3,4,5,6,7,8,9,10])

even_num = num[num % 2 == 0]

print(even_num)

[ 2  4  6  8 10]


**Fancy Indexing**

In [4]:
num2 = np.array([1,2,3,4,5,6,7,8,9])

ele = num2[[1,2,3,4]]

print(ele)

[2 3 4 5]


In [5]:
# arange function

a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [8]:
r_n = np.random.randint(1,100)
print(r_n)

46


In [10]:
r_n = np.random.rand(5)
print(r_n)

[0.37958581 0.29605874 0.08134822 0.33356697 0.84028762]
