#Data Preprocessing


In [81]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [82]:
dataset = pd.read_csv('/content/Dataset_master.xlsx - American Express User Exit Pred.csv')
X = dataset.iloc[:,0:-1].values
y = dataset.iloc[:,-1].values

In [83]:
print(X)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


In [84]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [85]:
print(X)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


In [86]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')

X = np.array(ct.fit_transform(X))

In [87]:
print(X)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


In [88]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [89]:
len(X_train)

7941

In [90]:
len(y_train)

7941

In [91]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [92]:
print(X_train)

[[ 0.99434917 -0.57109746 -0.5792406  ...  0.90580857  0.65086753
  -0.06854301]
 [-1.00568294 -0.57109746  1.72639831 ...  0.90580857  0.65086753
   0.34018176]
 [ 0.99434917 -0.57109746 -0.5792406  ... -0.951175   -1.53641095
  -0.67326188]
 ...
 [-1.00568294 -0.57109746  1.72639831 ... -0.951175    0.65086753
  -0.17067658]
 [-1.00568294 -0.57109746  1.72639831 ... -0.951175    0.65086753
   1.4232319 ]
 [ 0.99434917 -0.57109746 -0.5792406  ... -0.951175   -1.53641095
  -1.67963883]]


#ANN

#Initializing

In [93]:
ann = tf.keras.models.Sequential()

# Adding input layer and first hidden layer

In [94]:
ann.add(tf.keras.layers.Dense(units = 6 ,activation = 'relu'))

# Adding second hidden layer

In [95]:
ann.add(tf.keras.layers.Dense(units = 6 ,activation = 'relu'))

# Adding output layer

In [96]:
ann.add(tf.keras.layers.Dense(units = 1 , activation = 'sigmoid'))

# ANN training

In [97]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

In [98]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 120)

Epoch 1/120
249/249 [==============================] - 4s 5ms/step - loss: 0.7818 - accuracy: 0.4327
Epoch 2/120
249/249 [==============================] - 1s 6ms/step - loss: 0.5268 - accuracy: 0.7911
Epoch 3/120
249/249 [==============================] - 1s 5ms/step - loss: 0.4646 - accuracy: 0.7998
Epoch 4/120
249/249 [==============================] - 1s 5ms/step - loss: 0.4469 - accuracy: 0.8037
Epoch 5/120
249/249 [==============================] - 1s 4ms/step - loss: 0.4347 - accuracy: 0.8061
Epoch 6/120
249/249 [==============================] - 1s 4ms/step - loss: 0.4256 - accuracy: 0.8086
Epoch 7/120
249/249 [==============================] - 1s 3ms/step - loss: 0.4193 - accuracy: 0.8095
Epoch 8/120
249/249 [==============================] - 1s 4ms/step - loss: 0.4140 - accuracy: 0.8125
Epoch 9/120
249/249 [==============================] - 1s 3ms/step - loss: 0.4099 - accuracy: 0.8131
Epoch 10/120
249/249 [==============================] - 1s 3ms/step - loss: 0.4062 - accura

In [101]:
print(ann.predict(sc.transform([[0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]])) > 0.5)

1/1 [==============================] - 0s 95ms/step
[[False]]


In [103]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [1 1]]


In [105]:
from sklearn.metrics import confusion_matrix,accuracy_score

cm = confusion_matrix(y_pred,y_test)
print(cm)
accuracy_score(y_pred,y_test)

[[1503  229]
 [  70  184]]


0.8494461228600202