In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
dataset = pd.read_csv("/kaggle/input/model-selection/Model Selection.csv")
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [17]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [18]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [28]:
print(X_train)
len(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


7654

In [29]:
print(y_train)
len(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


7654

In [30]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [32]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)

array([[431.43, 431.23],
       [458.56, 460.01],
       [462.75, 461.14],
       ...,
       [469.52, 473.26],
       [442.42, 438.  ],
       [461.88, 463.28]])

In [33]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

0.9277905636321646